/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2022-03-02 08:27:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.recipe2_0028member_0029;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class recipeInsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1\">\r\n");
      out.write("  <meta http-equiv=\"Content-Security-Policy\" content=\"upgrade-insecure-requests\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("   <title>freeBoard</title>\r\n");
      out.write("	<link rel='stylesheet' href='css/bootstrap.css' />\r\n");
      out.write("    <link rel='stylesheet' href='stylesheets/fb_style.css' />\r\n");
      out.write("   <link rel='stylesheet' href='stylesheets/normalize.css' />\r\n");
      out.write("  <link rel='stylesheet' href='stylesheets/style.css' />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"stylesheets/swiper.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"stylesheets/swiper.css\">\r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.5.1.js\" integrity=\"sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=\"\r\n");
      out.write("    crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"//wcs.naver.net/wcslog.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <!-- jQuery (부트스트랩의 자바스크립트 플러그인을 위해 필요합니다) -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("    <!-- 모든 컴파일된 플러그인을 포함합니다 (아래), 원하지 않는다면 필요한 각각의 파일을 포함하세요 -->\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <div id=\"header\">\r\n");
      out.write("     <div class=\"headerCon\">\r\n");
      out.write("      <div class=\"headerTop\">\r\n");
      out.write("        <ul class=\"headerMenu\">\r\n");
      out.write("          \r\n");
      out.write("            <li><a href=\"#\">로그인</a></li>\r\n");
      out.write("            <li><a href=\"#\">회원가입</a></li>\r\n");
      out.write("            <li><a href=\"/mypage\">마이페이지</a></li>\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("   <div class=\"m_headerCon\">\r\n");
      out.write("    <ul class=\"m_topMenu\">\r\n");
      out.write("         <!-- <li><a class=\"logoB\" href=\"/\"><img class=\"logo\" src=\"../images/clogo-n.svg\" /></a></li> -->\r\n");
      out.write("          <li><a class=\"logoB\" href=\"/\"><img class=\"logo\" src=\"images/cookk_png.png\" /></a></li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <form class=\"searchF\" action=\"/search\" method=\"get\">\r\n");
      out.write("                <input type=\"search\" name=\"keyword\" class=\"search\" placeholder=\"레시피를 검색 해보세요.\" />\r\n");
      out.write("                 <input type=\"image\" name=\"submit\" value=\"submit\" src=\"images/search_png.png\" \r\n");
      out.write("                 						style=\"width:30px; margin-left:3px; vertical-align:middle\"/>\r\n");
      out.write("            </form>\r\n");
      out.write("            <script>\r\n");
      out.write("                $(document).ready(function () {\r\n");
      out.write("                    var keyword = getParameter(\"keyword\");\r\n");
      out.write("\r\n");
      out.write("                    if (keyword) {\r\n");
      out.write("                        $(\".search\").val(keyword);\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                function getParameter(name) {\r\n");
      out.write("                    name = name.replace(/[\\[]/, \"\\\\[\").replace(/[\\]]/, \"\\\\]\");\r\n");
      out.write("                    var regex = new RegExp(\"[\\\\?&]\" + name + \"=([^&#]*)\"),\r\n");
      out.write("                        results = regex.exec(location.search);\r\n");
      out.write("                    return results === null ? \"\" : decodeURIComponent(results[1].replace(/\\+/g, \" \"));\r\n");
      out.write("                }\r\n");
      out.write("            </script>\r\n");
      out.write("        </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"gnbRight\">\r\n");
      out.write("        <ul class=\"gnb\">\r\n");
      out.write("            <li><a href=\"/recipe1\">레시피1</a></li>\r\n");
      out.write("            <li><a href=\"/recipe2\">레시피2</a></li>\r\n");
      out.write("            <li><a href=\"/freeboard\">자유게시판</a></li>\r\n");
      out.write("            <li><a href=\"/event\">이벤트</a></li>\r\n");
      out.write("            <!--<li><a href=\"/edu/detail\">서비스</a></li>-->\r\n");
      out.write("          <!--   <li><a href=\"/mypage\">마이페이지</a></li> -->\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div><!-- m_headerCon -->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function () {\r\n");
      out.write("        var sc = $(\".gnbRight\").offset();\r\n");
      out.write("        //console.log(sc);\r\n");
      out.write("        //console.log($(document).scrollTop());\r\n");
      out.write("\r\n");
      out.write("        $(window).scroll(function () {\r\n");
      out.write("            //console.log($(document).scrollTop());\r\n");
      out.write("            if ($(document).scrollTop() > sc.top) {\r\n");
      out.write("                $(\".gnbRight\").addClass(\"menu_fixed\");\r\n");
      out.write("            }\r\n");
      out.write("            else {\r\n");
      out.write("                $(\".gnbRight\").removeClass(\"menu_fixed\");\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("      <div class=\"gnbCon\">\r\n");
      out.write("    <div class=\"gnbBox\">\r\n");
      out.write("        <div class=\"gnbLeft\">\r\n");
      out.write("      <!--  <a href=\"/\"><img class=\"logo\" src=\"../images/clogo-n.svg\" /></a> -->\r\n");
      out.write("             <a href=\"/\"><img class=\"logo\" src=\"../images/cookk_png.png\" /></a>\r\n");
      out.write("            <form class=\"searchF\" action=\"/search\" method=\"get\">\r\n");
      out.write("                <input type=\"text\" name=\"keyword\" class=\"search\" placeholder=\"레시피를 검색 해보세요.\" />\r\n");
      out.write("                 <input type=\"image\" name=\"submit\" value=\"submit\" src=\"../images/search_png.png\" \r\n");
      out.write("                 						style=\"width:30px; margin-left:3px; vertical-align:middle\"/>\r\n");
      out.write("            </form>\r\n");
      out.write("            <script>\r\n");
      out.write("                $(document).ready(function () {\r\n");
      out.write("                    var keyword = getParameter(\"keyword\");\r\n");
      out.write("\r\n");
      out.write("                    if (keyword) {\r\n");
      out.write("                        $(\".search\").val(keyword);\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                function getParameter(name) {\r\n");
      out.write("                    name = name.replace(/[\\[]/, \"\\\\[\").replace(/[\\]]/, \"\\\\]\");\r\n");
      out.write("                    var regex = new RegExp(\"[\\\\?&]\" + name + \"=([^&#]*)\"),\r\n");
      out.write("                        results = regex.exec(location.search);\r\n");
      out.write("                    return results === null ? \"\" : decodeURIComponent(results[1].replace(/\\+/g, \" \"));\r\n");
      out.write("                }\r\n");
      out.write("            </script>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"gnbRight\">\r\n");
      out.write("            <ul class=\"gnb\">\r\n");
      out.write("                <li><a href=\"/recipe1\">레시피1</a></li>\r\n");
      out.write("	            <li><a href=\"/recipe2\">레시피2</a></li>\r\n");
      out.write("	            <li><a href=\"/freeboard\">자유게시판</a></li>\r\n");
      out.write("	            <li><a href=\"/event\">이벤트</a></li>\r\n");
      out.write("                <!--<li><a href=\"/edu/detail\">서비스</a></li>-->\r\n");
      out.write("                <!-- <li><a href=\"/mypage\">MY</a></li> -->\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("    	</div><!-- gnbBox -->\r\n");
      out.write("	</div> <!-- gnbCon -->\r\n");
      out.write("\r\n");
      out.write("</div><!-- header -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("	<div class=\"container con_wrap\">\r\n");
      out.write("		<div class=\"con_box\">\r\n");
      out.write("			<div class=\"con_title\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<img src=\"../images/spoon.png\"/>\r\n");
      out.write("				</div>\r\n");
      out.write("				<h1><b>쿸투게더</b></h1>\r\n");
      out.write("			</div>\r\n");
      out.write("			<span class=\"btn_write\">	\r\n");
      out.write("			    <input type=\"button\" onclick=\"writeForm.jsp\" value=\"글쓰기\">\r\n");
      out.write("			</span>\r\n");
      out.write("			<div class=\"view_tab\">\r\n");
      out.write("				<select>\r\n");
      out.write("					<option>조회순</option>\r\n");
      out.write("					<option>오래된순</option>\r\n");
      out.write("					<option>최신순</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"table-responsive con_table\">\r\n");
      out.write("			<table class=\"table table-hover\" width=\"800\" \r\n");
      out.write("			cellpadding=\"0\" cellspacing=\"0\" > \r\n");
      out.write("				<thead>\r\n");
      out.write("			    	<tr height=\"30\"> \r\n");
      out.write("				      <td>no</td> \r\n");
      out.write("				      <td>제   목</td> \r\n");
      out.write("				      <td>작성자</td>\r\n");
      out.write("				      <td>작성일</td> \r\n");
      out.write("				      <td>조 회</td> \r\n");
      out.write("			  	  </tr>\r\n");
      out.write("			    </thead>\r\n");
      out.write("			    <tr>\r\n");
      out.write("			    	<td>1</td><td>안녕하세요</td><td>이지은</td>\r\n");
      out.write("			    	<td>22-03-01</td><td>3</td>\r\n");
      out.write("			    </tr>\r\n");
      out.write("			    <tr>\r\n");
      out.write("			    	<td>2</td><td>안녕하세요</td><td>이예은</td>\r\n");
      out.write("			    	<td>22-03-01</td><td>3</td>\r\n");
      out.write("			    </tr>\r\n");
      out.write("			    <tr>\r\n");
      out.write("			    	<td>3</td><td>안녕하세요</td><td>김예린</td>\r\n");
      out.write("			    	<td>22-03-01</td><td>3</td>\r\n");
      out.write("			    </tr>\r\n");
      out.write("			    <tr>\r\n");
      out.write("			    	<td>4</td><td>안녕하세요</td><td>주정운</td>\r\n");
      out.write("			    	<td>22-03-01</td><td>3</td>\r\n");
      out.write("			    </tr>\r\n");
      out.write("			    <tr>\r\n");
      out.write("			    	<td>5</td><td>안녕하세요</td><td>홍지원</td>\r\n");
      out.write("			    	<td>22-03-01</td><td>3</td>\r\n");
      out.write("			    </tr>\r\n");
      out.write("			\r\n");
      out.write("			  <!--  <tr height=\"30\">\r\n");
      out.write("			    <td align=\"center\"  width=\"50\" ></td>\r\n");
      out.write("			    <td  width=\"250\" ></td>\r\n");
      out.write("			    <td align=\"center\"  width=\"100\"> </td>\r\n");
      out.write("			    <td align=\"center\"  width=\"150\"></td>\r\n");
      out.write("			    <td align=\"center\"  width=\"50\"></td>\r\n");
      out.write("			    <td align=\"center\" width=\"100\" ></td>\r\n");
      out.write("			  </tr>-->\r\n");
      out.write("			</table>\r\n");
      out.write("			</div> <!-- table-responsive con_table -->\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"paging\">\r\n");
      out.write("				<ul class=\"pagination pagination-xs\">\r\n");
      out.write("				 	<li><a href=\"#\"> << </a></li>\r\n");
      out.write("				 	<li class=\"active\"><a href=\"#\">1</a></li>\r\n");
      out.write("				 	<li><a href=\"#\">2</a></li>\r\n");
      out.write("				 	<li><a href=\"#\">3</a></li>\r\n");
      out.write("				 	<li><a href=\"#\">4</a></li>\r\n");
      out.write("				 	<li><a href=\"#\">5</a></li>\r\n");
      out.write("				 	<li><a href=\"#\">6</a></li>\r\n");
      out.write("				 	<li><a href=\"#\">7</a></li>\r\n");
      out.write("				 	<li><a href=\"#\">8</a></li>\r\n");
      out.write("				 	<li><a href=\"#\">9</a></li>\r\n");
      out.write("				 	<li><a href=\"#\">10</a></li>\r\n");
      out.write("				 	<li><a href=\"#\"> >> </a></li>\r\n");
      out.write("				 </ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("		</div> <!-- conbox -->\r\n");
      out.write("	</div> <!-- container -->\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div id=\"footer\">\r\n");
      out.write("    <div class=\"container\" >\r\n");
      out.write("    <div class=\"footerBox\" >\r\n");
      out.write("        <div class=\"footerLeft\">\r\n");
      out.write("            <span class=\"ck\">Cookk</span>\r\n");
      out.write("            <ul class=\"ftmenu1\">\r\n");
      out.write("            <!-- <div class=\"ftR\">\r\n");
      out.write("                <p class=\"customer\">고객센터<span class=\"cthour\">오전 10시~오후6시(주말, 공휴일 제외)</span></p>\r\n");
      out.write("                <button type=\"button\" class=\"kakaoCS\" id=\"kakao-talk-channel-chat-button\">카카오톡 문의하기</button>\r\n");
      out.write("            </div> -->\r\n");
      out.write("            <p class=\"footerTxt\">\r\n");
      out.write("                쿸 <br />\r\n");
      out.write("                사업장: 서울특별시 강남구 역삼동 819-10 세경빌딩 3층<br />\r\n");
      out.write("                고객센터: cookk@cookk.com<br />\r\n");
      out.write("                연락처: 070-123-4567<br /><br />\r\n");
      out.write("                Copyright ⓒ 4조 All rights Reserved\r\n");
      out.write("            </p>\r\n");
      out.write("            <p class=\"m_footerTxt\">\r\n");
      out.write("                쿸 <br />\r\n");
      out.write("                사업장: 서울특별시 강남구 역삼동 819-10 세경빌딩 3층<br />\r\n");
      out.write("                고객센터: cookk@cookk.com<br />\r\n");
      out.write("                연락처: 070-123-4567<br /><br />\r\n");
      out.write("                Copyright ⓒ 4조 All rights Reserved\r\n");
      out.write("            </p>\r\n");
      out.write("               <!--  <li><a href=\"/about\">회사소개</a></li> -->\r\n");
      out.write("                <!--<li><a href=\"#\">채용</a></li>-->\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"ftmenu2\">\r\n");
      out.write("                <li><a href=\"/terms\" target=\"_blank\">이용약관</a></li>\r\n");
      out.write("                <li><a href=\"/privacy\" target=\"_blank\">개인정보취급방침</a></li>\r\n");
      out.write("                <li><a href=\"https://www.ftc.go.kr/www/bizCommView.do?key=232&apv_perm_no=2020409035430201403&pageUnit=10&searchCnd=wrkr_no&searchKrwd=4082821450&pageIndex=1\"\r\n");
      out.write("                        target=\"_blank\">사업자정보확인</a></li>\r\n");
      out.write("                <li><a href=\"/pdfs/cookmin_rule.pdf\" target=\"_blank\">쿸 규정</a></li>\r\n");
      out.write("                <li><a href=\"/pdfs/cookmin_guide.pdf\" target=\"_blank\">쿸 가이드라인</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      <div class=\"footerRight\" >\r\n");
      out.write("      		<div class=\"ftR\">\r\n");
      out.write("        		<ul>\r\n");
      out.write("        			<li><a href=\"#\"><img src=\"../images/insta.png\" alt=\"인스타그램\"/></a></li>\r\n");
      out.write("        			<li><a href=\"#\"><img src=\"../images/facebook.png\" alt=\"페이스북\"/></a></li>\r\n");
      out.write("        			<li><a href=\"#\"><img src=\"../images/twt.png\" alt=\"트위터\"/></a></li>\r\n");
      out.write("        			<li><a href=\"#\"><img src=\"../images/youtube.png\" alt=\"유튜브\"/></a></li>\r\n");
      out.write("        		</ul>\r\n");
      out.write("        	</div>\r\n");
      out.write("\r\n");
      out.write("              <!-- <div class=\"ftR\">\r\n");
      out.write("                <p class=\"customer\">고객센터<span class=\"cthour\">오전 10시~오후6시(주말, 공휴일 제외)</span></p>\r\n");
      out.write("                <button type=\"button\" class=\"kakaoCS\" id=\"kakao-talk-channel-chat-button\">카카오톡 문의하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p class=\"footerTxt\">\r\n");
      out.write("                더쿡민 | 대표: Hoon Lee | 개인정보보호책임자: Hoon Lee | 사업자등록번호: 408-28-21450<br />통신판매업신고:\r\n");
      out.write("                2020-경기김포-1416 | 사업장: 경기도 김포시 김포한강로2로 113 | 고객센터: thecookmin@kakao.com<br /><br />\r\n");
      out.write("                더쿡민은 통신판매중개자이며 통신판매의 당사자가 아닙니다. 따라서 더쿡민의 상품, 거래정보 및 거래에 대하여 책임을 지지 않습니다.\r\n");
      out.write("            </p>\r\n");
      out.write("            <p class=\"m_footerTxt\">\r\n");
      out.write("                더쿡민 | 대표: Hoon Lee | 개인정보보호책임자: Hoon Lee | 사업자등록번호: 408-28-21450 통신판매업신고:\r\n");
      out.write("                2020-경기김포-1416 | 사업장: 경기도 김포시 김포한강로2로 113 | 고객센터: thecookmin@kakao.com<br /><br />\r\n");
      out.write("                더쿡민은 통신판매중개자이며 통신판매의 당사자가 아닙니다. 따라서 더쿡민의 상품, 거래정보 및 거래에 대하여 책임을 지지 않습니다.\r\n");
      out.write("            </p> -->\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"m_footer_menu\">\r\n");
      out.write("    <ul>\r\n");
      out.write("        <li><a href=\"/\"><img class=\"icon\" src=\"../images/home.svg\" /><span>홈</span></a></li>\r\n");
      out.write("        <li><a href=\"/rsearch\"><img class=\"icon\" src=\"../images/loupe.svg\" /><span>요리검색</span></a></li>\r\n");
      out.write("        <li><a href=\"/mypage\"><img class=\"icon\" src=\"../images/user.svg\" /><span>마이페이지</span></a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function () {\r\n");
      out.write("        var path = window.location.pathname;\r\n");
      out.write("        if (path === \"/\") {\r\n");
      out.write("            $(\".m_footer_menu ul li:nth-child(1) a span\").css(\"color\", \"#e86416\");\r\n");
      out.write("        } else if (path === \"/rsearch\") {\r\n");
      out.write("            $(\".m_footer_menu ul li:nth-child(2) a span\").css(\"color\", \"#e86416\");\r\n");
      out.write("        } else if (path === \"/mypage\") {\r\n");
      out.write("            $(\".m_footer_menu ul li:nth-child(3) a span\").css(\"color\", \"#e86416\");\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    </div><!-- wrap -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
